In [1]:
import numpy as np

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10, 2.5
    )

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [6]:
a = [1, 2, 3, 4, 5, 6]

In [8]:
a = np.array(a)

In [13]:
a[2] = 10
a

array([ 1,  2, 10,  4,  5,  6])

In [15]:

np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [18]:
list(range(10))


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [19]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [20]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [25]:
m = np.array([[1, 2, 3],
          [2, 3, 4],
          [5, 6, 7]])

In [27]:
m[1, 2] = 100
m

array([[  1,   2,   3],
       [  2,   3, 100],
       [  5,   6,   7]])

In [28]:
np.random.rand(5, 2)

array([[0.95916223, 0.77743735],
       [0.50663871, 0.48135576],
       [0.0420384 , 0.88256696],
       [0.06257214, 0.23036148],
       [0.101684  , 0.38141028]])

In [29]:
np.random.randn(5, 2)

array([[-0.3156833 ,  0.34864153],
       [-0.81280509, -0.87044808],
       [ 0.1694205 ,  0.06748648],
       [ 0.67040696,  0.06972406],
       [ 0.31983879, -1.48075363]])

In [30]:
np.random.seed(2025)
np.random.rand(5, 2)

array([[0.13548816, 0.8878517 ],
       [0.93260564, 0.44556816],
       [0.38823555, 0.25759644],
       [0.65736759, 0.49261694],
       [0.96423842, 0.80098447]])

In [37]:
np.random.randint(low=0, high=100, size=(5, 2))

array([[98, 61],
       [36, 96],
       [59, 98],
       [16, 15],
       [86, 22]], dtype=int32)

In [38]:
a  = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [40]:
a + 1

array([1, 2, 3, 4, 5])